apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: documentation
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: documentation
    spec:
      containers:
      - name: documentation
        image: ${DOCKER_IMAGE}
        resources:
          requests:
            memory: "256M"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1