# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Armory.io Documentation
email: hello@armory.io
description: > # this means to ignore newlines until "baseurl:"
  Ship better software, faster, with Armory. Our platform is powered by Spinnaker, the open-source continuous software delivery platform from Netflix and Google.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - .idea
  - .assets-cache
  - bin/
  - Dockerfile
  - Jenkinsfile
  - README.md
keep_files: [images]
assets:
  sources:
    - _assets/css
  compress:
    css: true
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

collections:
  overview:
    output: true
    permalink: /overview/:title/
  spinnaker:
    output: true
    permalink: /spinnaker/:title/
  spinnaker_user_guides:
    output: true
    permalink: /spinnaker-user-guides/:title/
  spinnaker_install_admin_guides:
    output: true
    permalink: /spinnaker-install-admin-guides/:title/
  user_guides:
    output: true
    permalink: /user-guides/:title/
  install_guide:
    output: true
    permalink: /install-guide/:title/
  admin_guides:
    output: true
    permalink: /admin-guides/:title/
  release_notes:
    output: true
    permalink: /release-notes/:title/
  glossary:
    output: true
    permalink: /glossary/:title/
