languageCode = "en-us"
title = "Armory Spinnaker Documentation"
baseURL = "http://192.168.99.100:8080"
theme = "hugo-theme-learn"

[params]
  menu = [ "introduction", "installation", "related", "release-notes" ]